artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/9_Finale/9_Finale/YOLOv8n/runs/mlflow/902915270995896225/eff530d40334438cb685aeb1b0e088f6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '902915270995896225'
lifecycle_stage: active
run_id: eff530d40334438cb685aeb1b0e088f6
run_name: YOLOv8n-2
source_name: ''
source_type: 4
source_version: ''
start_time: 1782125926616
status: 1
tags: []
user_id: Axioo Pongo
