artifact_location: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv11n/runs/mlflow/822956362600978669
creation_time: 1780968756473
experiment_id: '822956362600978669'
last_update_time: 1780968756473
lifecycle_stage: active
name: c:\Users\Axioo Pongo\Desktop\All_in_One\College\Tugas Akhir\Pre-Processing Backup\Pre-Processing\8_Training_Tugas_Akhir\Trained_Models
trace_location: null
workspace: default
