artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv8n/runs/mlflow/659488275596038973/237def259c614571a127f4c5eb060d1c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '659488275596038973'
lifecycle_stage: active
run_id: 237def259c614571a127f4c5eb060d1c
run_name: ImageFixYOLOv8n
source_name: ''
source_type: 4
source_version: ''
start_time: 1781181067683
status: 1
tags: []
user_id: Axioo Pongo
