artifact_location: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv8n/runs/mlflow/659488275596038973
creation_time: 1780977085362
experiment_id: '659488275596038973'
last_update_time: 1780977085362
lifecycle_stage: active
name: c:\Users\Axioo Pongo\Desktop\All_in_One\College\Tugas Akhir\Pre-Processing Backup\Pre-Processing\8_Training_Tugas_Akhir\Trained_Models
trace_location: null
workspace: default
