artifact_location: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/9_Finale/9_Finale/YOLOv10n/runs/mlflow/759207407518714000
creation_time: 1782125584851
experiment_id: '759207407518714000'
last_update_time: 1782125584851
lifecycle_stage: active
name: c:\Users\Axioo Pongo\Desktop\All_in_One\College\Tugas Akhir\Pre-Processing Backup\Pre-Processing\9_Finale\9_Finale\Trained_Models
trace_location: null
workspace: default
