artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/9_Github_Transfer_David/tugas_akhir/9_Finale/YOLOv10n/runs/mlflow/866420479812078329/27c29890ba21407e91c34c3035fc74f9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '866420479812078329'
lifecycle_stage: active
run_id: 27c29890ba21407e91c34c3035fc74f9
run_name: YOLOv10n
source_name: ''
source_type: 4
source_version: ''
start_time: 1782027179009
status: 1
tags: []
user_id: Axioo Pongo
