artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv11n/runs/mlflow/822956362600978669/bf8e30474c684fed8f72040bbfda33f6/artifacts
end_time: 1781164039592
entry_point_name: ''
experiment_id: '822956362600978669'
lifecycle_stage: active
run_id: bf8e30474c684fed8f72040bbfda33f6
run_name: ImageFixYOLO11n
source_name: ''
source_type: 4
source_version: ''
start_time: 1781160914527
status: 3
tags: []
user_id: Axioo Pongo
