artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv8n/runs/mlflow/659488275596038973/befb01183072404e936466d65325a7b0/artifacts
end_time: 1780978825174
entry_point_name: ''
experiment_id: '659488275596038973'
lifecycle_stage: active
run_id: befb01183072404e936466d65325a7b0
run_name: YOLOv8n4
source_name: ''
source_type: 4
source_version: ''
start_time: 1780977086191
status: 3
tags: []
user_id: Axioo Pongo
