artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv11n/runs/mlflow/822956362600978669/00f14281e6414910925daaa0997fcd26/artifacts
end_time: 1780971288084
entry_point_name: ''
experiment_id: '822956362600978669'
lifecycle_stage: active
run_id: 00f14281e6414910925daaa0997fcd26
run_name: YOLO11n
source_name: ''
source_type: 4
source_version: ''
start_time: 1780968757584
status: 3
tags: []
user_id: Axioo Pongo
