artifact_location: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/9_Finale/9_Finale/YOLOv8n/runs/mlflow/902915270995896225
creation_time: 1782125926211
experiment_id: '902915270995896225'
last_update_time: 1782125926211
lifecycle_stage: active
name: c:\Users\Axioo Pongo\Desktop\All_in_One\College\Tugas Akhir\Pre-Processing Backup\Pre-Processing\9_Finale\9_Finale\Trained_Models
trace_location: null
workspace: default
