"""
Hand Gesture Recognition — Training Pipeline
=============================================
Input  : dataset/<class>/*.csv  (recorded by dataset_recorder.py)
Output : models/model.h              - C header (emlearn RandomForest)
         models/scaler_params.h      - normalisation constants for ESP32
         models/scaler.json          - same params in JSON
         models/plot_confusion.png   - confusion matrix with labels
         models/plot_roc.png         - ROC curves (one-vs-rest per class)
         models/plot_learning.png    - learning curves (train vs CV score)

Usage:
    python train.py
"""

import json
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, learning_curve, StratifiedKFold
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.metrics import (
    classification_report, ConfusionMatrixDisplay,
    roc_curve, auc,
)
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import emlearn

# ── Config ────────────────────────────────────────────────────────────────────
DATASET_DIR = Path("dataset")
MODELS_DIR  = Path("models")

# Only include classes that have data
CLASSES = ["right", "left", "up", "down", "idle"]

# Must match the CSV column order (excluding 'timestamp')
CHANNELS = ["ax1", "ay1", "az1", "gx1", "gy1", "gz1",
            "ax2", "ay2", "az2", "gx2", "gy2", "gz2"]

N_SAMPLES = 25      # rows per window (matches typical gesture duration at ~10 Hz)
IDLE_STRIDE = N_SAMPLES  # non-overlapping windows for idle class

RF_ESTIMATORS = 20
RF_MAX_DEPTH  = 15
# ──────────────────────────────────────────────────────────────────────────────


def pad_or_truncate(df: pd.DataFrame, n: int) -> pd.DataFrame:
    if len(df) >= n:
        return df.iloc[:n].reset_index(drop=True)
    pad = pd.concat([df.iloc[[-1]]] * (n - len(df)), ignore_index=True)
    return pd.concat([df, pad], ignore_index=True)


def sliding_windows(df: pd.DataFrame, n: int, stride: int):
    for start in range(0, len(df) - n + 1, stride):
        yield df.iloc[start : start + n]


def compute_features(window: pd.DataFrame) -> np.ndarray:
    """
    5 statistics × 12 channels = 60 features per window.
    Order: [mean_ch0..11, std_ch0..11, min_ch0..11, max_ch0..11, rms_ch0..11]
    Must stay in sync with feature_extractor.h on the ESP32.
    """
    arr = window[CHANNELS].values.astype(np.float32)  # (N_SAMPLES, 12)
    mean = arr.mean(axis=0)
    std  = arr.std(axis=0)
    mn   = arr.min(axis=0)
    mx   = arr.max(axis=0)
    rms  = np.sqrt((arr ** 2).mean(axis=0))
    return np.concatenate([mean, std, mn, mx, rms])   # shape (60,)


def load_dataset():
    X, y = [], []
    print("Loading dataset:")
    for label, cls in enumerate(CLASSES):
        folder = DATASET_DIR / cls
        if not folder.exists():
            print(f"  [skip] {cls} — folder not found")
            continue

        files = sorted(folder.glob("*.csv"))
        if not files:
            print(f"  [skip] {cls} — no CSV files")
            continue

        count = 0
        for f in files:
            df = pd.read_csv(f)
            if df.empty or not all(c in df.columns for c in CHANNELS):
                continue

            if cls == "idle":
                for win in sliding_windows(df, N_SAMPLES, IDLE_STRIDE):
                    X.append(compute_features(win))
                    y.append(label)
                    count += 1
            else:
                win = pad_or_truncate(df, N_SAMPLES)
                X.append(compute_features(win))
                y.append(label)
                count += 1

        print(f"  {cls:<22} {count:>4} samples")

    return np.array(X, dtype=np.float32), np.array(y, dtype=np.int32)


def save_scaler_header(params: dict, path: Path):
    n      = params["n_features"]
    mean_s = ", ".join(f"{v:.6f}f" for v in params["mean"])
    std_s  = ", ".join(f"{v:.6f}f" for v in params["std"])
    names  = "\n".join(f'    "{c}",' for c in params["classes"])

    header = f"""\
#pragma once
// Auto-generated by train.py — do not edit manually.

#define N_FEATURES  {n}
#define N_CLASSES   {len(params["classes"])}

const char* CLASS_NAMES[N_CLASSES] = {{
{names}
}};

const float SCALER_MEAN[N_FEATURES] = {{ {mean_s} }};
const float SCALER_STD[N_FEATURES]  = {{ {std_s}  }};

inline void normalize_features(float* features) {{
    for (int i = 0; i < N_FEATURES; i++) {{
        features[i] = (features[i] - SCALER_MEAN[i]) / SCALER_STD[i];
    }}
}}
"""
    path.write_text(header)


def plot_confusion(y_true, y_pred, class_names, path: Path):
    fig, ax = plt.subplots(figsize=(7, 6))
    disp = ConfusionMatrixDisplay.from_predictions(
        y_true, y_pred, display_labels=class_names,
        ax=ax, colorbar=False, cmap="Blues",
    )
    # Annotate each cell with count AND percentage
    cm = disp.confusion_matrix
    total = cm.sum(axis=1, keepdims=True)
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            pct = 100 * cm[i, j] / total[i, 0] if total[i, 0] > 0 else 0
            ax.text(j, i + 0.25, f"({pct:.0f}%)",
                    ha="center", va="center", fontsize=8, color="grey")

    ax.set_title("Confusion Matrix", fontsize=13, fontweight="bold", pad=12)
    ax.set_xlabel("Predicted label", fontsize=10)
    ax.set_ylabel("True label", fontsize=10)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()


def plot_roc(y_true, y_prob, class_names, path: Path):
    n_classes = len(class_names)
    # Binarise labels for one-vs-rest ROC
    y_bin = label_binarize(y_true, classes=list(range(n_classes)))

    palette = sns.color_palette("tab10", n_classes)

    fig, ax = plt.subplots(figsize=(7, 6))

    mean_aucs = []
    for i, cls in enumerate(class_names):
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_prob[:, i])
        roc_auc     = auc(fpr, tpr)
        mean_aucs.append(roc_auc)
        ax.plot(fpr, tpr, color=palette[i], lw=2,
                label=f"{cls}  (AUC = {roc_auc:.2f})")

    ax.plot([0, 1], [0, 1], "k--", lw=1, label="Random")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.02)
    ax.set_xlabel("False Positive Rate", fontsize=10)
    ax.set_ylabel("True Positive Rate", fontsize=10)
    ax.set_title(f"ROC Curves (One-vs-Rest)  |  mean AUC = {np.mean(mean_aucs):.3f}",
                 fontsize=12, fontweight="bold")
    ax.legend(loc="lower right", fontsize=9)
    ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()


def plot_learning(clf, X, y, path: Path):
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    train_sizes = np.linspace(0.1, 1.0, 10)

    train_sizes_abs, train_scores, val_scores = learning_curve(
        clf, X, y,
        cv=cv,
        train_sizes=train_sizes,
        scoring="accuracy",
        n_jobs=-1,
    )

    train_mean = train_scores.mean(axis=1)
    train_std  = train_scores.std(axis=1)
    val_mean   = val_scores.mean(axis=1)
    val_std    = val_scores.std(axis=1)

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.plot(train_sizes_abs, train_mean, "o-", color="#2196F3", lw=2, label="Train accuracy")
    ax.fill_between(train_sizes_abs,
                    train_mean - train_std, train_mean + train_std,
                    alpha=0.15, color="#2196F3")

    ax.plot(train_sizes_abs, val_mean, "o-", color="#FF5722", lw=2, label="CV accuracy")
    ax.fill_between(train_sizes_abs,
                    val_mean - val_std, val_mean + val_std,
                    alpha=0.15, color="#FF5722")

    ax.set_xlabel("Training samples", fontsize=10)
    ax.set_ylabel("Accuracy", fontsize=10)
    ax.set_ylim(0, 1.05)
    ax.set_title("Learning Curves  (5-fold CV)", fontsize=12, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()


def main():
    MODELS_DIR.mkdir(exist_ok=True)

    # ── Load & featurise ──────────────────────────────────────────────────────
    X, y = load_dataset()
    if len(X) == 0:
        print("No data found. Record some samples first.")
        return

    n_classes_found = len(np.unique(y))
    print(f"\nTotal: {len(X)} samples | {X.shape[1]} features | {n_classes_found} classes")

    # ── Normalise ─────────────────────────────────────────────────────────────
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    scaler_params = {
        "mean":       scaler.mean_.tolist(),
        "std":        scaler.scale_.tolist(),
        "n_features": int(X.shape[1]),
        "classes":    CLASSES,
    }
    with open(MODELS_DIR / "scaler.json", "w") as f:
        json.dump(scaler_params, f, indent=2)

    save_scaler_header(scaler_params, MODELS_DIR / "scaler_params.h")
    print("Saved  models/scaler.json, models/scaler_params.h")

    # ── Train ─────────────────────────────────────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42, stratify=y
    )

    print(f"\nTraining RandomForest  (n_estimators={RF_ESTIMATORS}, max_depth={RF_MAX_DEPTH}) …")
    clf = RandomForestClassifier(
        n_estimators=RF_ESTIMATORS,
        max_depth=RF_MAX_DEPTH,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)

    # ── Evaluate ──────────────────────────────────────────────────────────────
    y_pred      = clf.predict(X_test)
    y_prob      = clf.predict_proba(X_test)
    active_idx  = sorted(np.unique(y_test))
    active_cls  = [CLASSES[i] for i in active_idx]

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=active_cls))

    plot_confusion(y_test, y_pred, active_cls,  MODELS_DIR / "plot_confusion.png")
    plot_roc      (y_test, y_prob, active_cls,  MODELS_DIR / "plot_roc.png")
    plot_learning (clf, X_scaled, y,            MODELS_DIR / "plot_learning.png")

    print("Saved  models/plot_confusion.png")
    print("Saved  models/plot_roc.png")
    print("Saved  models/plot_learning.png")

    # ── Export C header ───────────────────────────────────────────────────────
    print("\nExporting model to C …")
    cmodel = emlearn.convert(clf, method="inline")
    cmodel.save(name="gesture_model", file=str(MODELS_DIR / "model.h"))
    print("Saved  models/model.h")

    print("\nDone! Copy these two files to your ESP32 sketch folder:")
    print("  models/model.h")
    print("  models/scaler_params.h")
    print("  esp32_inference/feature_extractor.h  (already there)")


if __name__ == "__main__":
    main()
