artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv8n/runs/mlflow/659488275596038973/ea33176ce87e4df083c82d9d02518d9d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '659488275596038973'
lifecycle_stage: active
run_id: ea33176ce87e4df083c82d9d02518d9d
run_name: YOLOv8n
source_name: ''
source_type: 4
source_version: ''
start_time: 1781532857908
status: 1
tags: []
user_id: Axioo Pongo
