"""
1D CNN export for ESP32 via TFLite Micro.

Step 1 (this script, runs on Python 3.14):
    Exports model.onnx + scaler_params.h + labels.h → output_tflite/

Step 2 (convert_to_tflite.py, needs Python ≤ 3.12 + TF):
    ONNX → TFLite → C array (model_data.h)
    Run on Google Colab or any machine with TensorFlow installed.

ESP32 TFLite Micro usage (pseudocode):
    #include "model_data.h"   // generated by convert_to_tflite.py
    #include "scaler_params.h"
    #include "labels.h"

    // Input tensor shape: [1, 25, 12] (batch=1, timesteps=25, channels=12)
    // 1. Fill input buffer with scaled IMU values
    for (int t = 0; t < WINDOW_SIZE; t++)
        for (int c = 0; c < N_IMU_CHANNELS; c++)
            input[t * N_IMU_CHANNELS + c] =
                (raw_window[t][c] - SCALER_MEAN[c]) / SCALER_STD[c];

    // 2. Run inference
    interpreter->Invoke();

    // 3. Read output (softmax probabilities for 5 classes)
    int class_idx = argmax(output, N_CLASSES);
    Serial.println(GESTURE_CLASSES[class_idx]);
"""

import os
import sys
import numpy as np
import joblib
import torch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from common.preprocessing import (
    load_file_list, get_class_names, WINDOW_SIZE, FEATURES,
)
from common.export_utils import (
    export_scaler_header, export_labels_header, write_convert_script,
)

# Import the model architecture from train.py
sys.path.insert(0, os.path.dirname(__file__))
from train import CNN1D

DATA_DIR    = os.path.join(os.path.dirname(__file__), "..", "cleaned_data")
MODEL_PT    = os.path.join(os.path.dirname(__file__), "output", "model.pt")
SCALER_PKL  = os.path.join(os.path.dirname(__file__), "output", "scaler.pkl")
OUTPUT_DIR  = os.path.join(os.path.dirname(__file__), "output_tflite")
os.makedirs(OUTPUT_DIR, exist_ok=True)

N_FEATURES = len(FEATURES)
MODEL_NAME = "cnn_1d"


def export_onnx(model: torch.nn.Module, path: str) -> None:
    model.eval()
    dummy = torch.zeros(1, WINDOW_SIZE, N_FEATURES)
    torch.onnx.export(
        model,
        dummy,
        path,
        input_names=["imu_window"],
        output_names=["class_probs"],
        dynamic_axes={"imu_window": {0: "batch"}, "class_probs": {0: "batch"}},
        opset_version=13,
        dynamo=False,
    )
    print(f"  Saved: {path}")

    # Validate
    import onnx
    onnx_model = onnx.load(path)
    onnx.checker.check_model(onnx_model)
    print("  ONNX model validated OK.")


def main() -> None:
    print("=" * 50)
    print("  1D CNN Export (Step 1/2)")
    print("=" * 50)

    if not os.path.exists(MODEL_PT) or not os.path.exists(SCALER_PKL):
        print("ERROR: Run cnn_1d/train.py first.")
        sys.exit(1)

    file_list   = load_file_list(DATA_DIR)
    class_names = get_class_names(file_list)
    num_classes = len(class_names)
    print(f"Classes ({num_classes}): {class_names}")

    scaler = joblib.load(SCALER_PKL)

    model = CNN1D(n_features=N_FEATURES, num_classes=num_classes)
    model.load_state_dict(torch.load(MODEL_PT, weights_only=True))
    model.eval()
    print("Model loaded.")

    onnx_path = os.path.join(OUTPUT_DIR, f"{MODEL_NAME}.onnx")
    print("\nExporting to ONNX...")
    export_onnx(model, onnx_path)

    export_scaler_header(
        scaler,
        os.path.join(OUTPUT_DIR, "scaler_params.h"),
        window_size=WINDOW_SIZE,
        n_features=N_FEATURES,
    )
    export_labels_header(
        class_names,
        os.path.join(OUTPUT_DIR, "labels.h"),
    )
    write_convert_script(
        os.path.join(OUTPUT_DIR, "convert_to_tflite.py"),
        onnx_filename=f"{MODEL_NAME}.onnx",
        model_name=MODEL_NAME,
    )

    print(f"\nStep 1 done. Files in: {OUTPUT_DIR}")
    print("\n--- Next: Step 2 (TFLite conversion) ---")
    print("TensorFlow does not support Python 3.14 yet.")
    print("Run convert_to_tflite.py in one of these environments:")
    print("  Option A — Google Colab (free, recommended):")
    print("    1. Open https://colab.research.google.com")
    print("    2. Upload output_tflite/cnn_1d.onnx")
    print(f"    3. Upload output_tflite/convert_to_tflite.py")
    print("    4. Run: !pip install onnx2tf tensorflow")
    print("    5. Run: !python convert_to_tflite.py")
    print("    6. Download model_data.h and scaler_params.h")
    print("  Option B — Local Python 3.11/3.12 venv:")
    print("    pip install tensorflow onnx2tf")
    print("    python convert_to_tflite.py")


if __name__ == "__main__":
    main()
