artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv11n/runs/mlflow/822956362600978669/6236e817859d4095b2ea81f0140643b6/artifacts
end_time: 1781524571227
entry_point_name: ''
experiment_id: '822956362600978669'
lifecycle_stage: active
run_id: 6236e817859d4095b2ea81f0140643b6
run_name: YOLO11n-2
source_name: ''
source_type: 4
source_version: ''
start_time: 1781522262369
status: 3
tags: []
user_id: Axioo Pongo
