artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/9_Github_Transfer_David/tugas_akhir/9_Finale/YOLOv10n/runs/mlflow/866420479812078329/e56938faa30e421991ebde1893ce9006/artifacts
end_time: 1782037443782
entry_point_name: ''
experiment_id: '866420479812078329'
lifecycle_stage: active
run_id: e56938faa30e421991ebde1893ce9006
run_name: YOLOv10n-3
source_name: ''
source_type: 4
source_version: ''
start_time: 1782030703567
status: 3
tags: []
user_id: Axioo Pongo
