artifact_uri: file:c:/Users/Axioo Pongo/Desktop/All_in_One/College/Tugas Akhir/Pre-Processing
  Backup/Pre-Processing/8_Training_Tugas_Akhir/YOLOv8n/runs/mlflow/659488275596038973/3eb7567725a9488584ad5c6d934ebfc3/artifacts
end_time: 1781185655752
entry_point_name: ''
experiment_id: '659488275596038973'
lifecycle_stage: active
run_id: 3eb7567725a9488584ad5c6d934ebfc3
run_name: ImageFixYOLOv8n
source_name: ''
source_type: 4
source_version: ''
start_time: 1781183138050
status: 3
tags: []
user_id: Axioo Pongo
